esphome:
  name: esp-s-pressure-temp-hum

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "89O650QHuaEJnQIXK6D9/6jP8TI1ROrnEMlkRiKDfNI="

ota:
  password: "02f09a371aa29acb9e3e7b8e21271f24"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-S-Pressure-Temp-Hum"
    password: "P6c4TFeIIqIZ"

i2c:
  sda: D2
  scl: D1
  scan: true
  id: bus_a

captive_portal:
    
# Example configuration entry
sensor:
  - platform: bmp280
    i2c_id: bus_a
    temperature:
      name: "BMP280 Temperature"
      accuracy_decimals: 2
      oversampling: 16x
    pressure:
      name: "BMP280 Pressure"
      accuracy_decimals: 4
    address: 0x76
    update_interval: 20s
