# yaml-language-server: $schema=http://192.168.0.24:8971/api/config/schema.json

# Optional: Database configuration
database:
  # The path to store the SQLite DB (default: shown below)
  path: /config/frigate.db
  
snapshots:
  enabled: True
  timestamp: true
  bounding_box: true
  retain:
    default: 30
mqtt:
  enabled: False
#  host: 192.168.200.14

record:
  enabled: True
  retain:
    days: 3
    mode: all
  alerts:
    retain:
      days: 30
      mode: motion
  detections:
    retain:
      days: 30
      mode: motion

ffmpeg:
  hwaccel_args: preset-vaapi

cameras:
  przyczepa:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://motioneye:ProsteHaslo1@192.168.60.117:554/Streaming/Channels/101/
          roles:
            - detect
            - record
    webui_url: "http://192.168.60.117"
